# Generated by Django 5.2 on 2025-04-12 15:38

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام طرح')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سنگ')),
                ('price_per_box_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت هر کارتن (دلار)')),
                ('stock_box', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی (کارتن)')),
            ],
            options={
                'verbose_name': 'سنگ',
                'verbose_name_plural': 'سنگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ هزینه')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیح اضافی')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='از تاریخ')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تا تاریخ')),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نرخ دلار')),
                ('total_pieces_sold', models.PositiveIntegerField(verbose_name='تعداد قواره\u200cها')),
                ('total_sales_amount', models.PositiveIntegerField(verbose_name='جمع فروش')),
                ('total_stone_cost', models.PositiveIntegerField(verbose_name='هزینه سنگ\u200cها')),
                ('total_expenses', models.PositiveIntegerField(verbose_name='جمع هزینه\u200cها')),
                ('net_profit', models.IntegerField(verbose_name='سود خالص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'گزارش مالی',
                'verbose_name_plural': 'گزارش\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ فاکتور')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='شماره فاکتور')),
                ('design_price_per_piece', models.PositiveIntegerField(verbose_name='قیمت هر قواره')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد قواره')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('total_price', models.PositiveIntegerField(verbose_name='جمع کل (محاسبه\u200cشده)')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('check', 'چک')], max_length=10, verbose_name='نوع پرداخت')),
                ('check_due_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ چک (در صورت وجود)')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیح چک')),
                ('amount_paid', models.PositiveIntegerField(verbose_name='مبلغ پرداخت\u200cشده')),
                ('remaining_debt', models.PositiveIntegerField(verbose_name='بدهی باقی\u200cمانده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='مشتری')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.design', verbose_name='طرح')),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stone', verbose_name='نوع سنگ')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداختی')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='مشتری')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_registered', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice', verbose_name='فاکتور مرتبط')),
            ],
            options={
                'verbose_name': 'پرداخت مشتری',
                'verbose_name_plural': 'پرداخت\u200cهای مشتریان',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ تراکنش')),
                ('quantity_box', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار (کارتن)')),
                ('type', models.CharField(choices=[('buy', 'خرید'), ('consume', 'مصرف')], max_length=10, verbose_name='نوع تراکنش')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stone', verbose_name='نوع سنگ')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
                'ordering': ['-date'],
            },
        ),
    ]
